### PR TITLE
fix: monitor and compare commands for mantle and mantle-testnet

### LINKED ISSUE #70: Mantle Mainnet Deployment Down
Joba reported that Mantle Mainnet payment-subgraph deployment is down. The FusionX Graph Node returns the following error:

```json
{
  "errors": [
    "{\n  \"errors\": [\n    {\n      \"message\": \"deployment `requestnetwork/request-payments-mantle` does not exist\"\n    }\n  ]\n}"
  ]
}
```

# Definition of Done

- [x] #71 
- [x] Re-create Mantle payments-subgraph by calling `yarn graph create --node https://deploy.graph.fusionx.finance requestnetwork/request-payments-mantle`
- [x] Re-deploy Mantle payments-subgraph https://github.com/RequestNetwork/payments-subgraph/actions/runs/6549427632/job/17786312245
- [x] Inform Joba that Mantle payments-subgraph is working again
- [x] Investigate why this happened https://github.com/RequestNetwork/private-issues/issues/37
- [ ] #72

### PR DESCRIPTION
**Pull request by MantisClone**
Towards #62
Closes #70 

# Problem

While debugging #70, I noticed that the `monitor` and `compare` CLI commands weren't updated to support mantle and mantle testnet as part of #62 but they should have been.

# Changes

* Fix the monitor and compare commands to work for mantle and mantle-testnet
  * Add graph-nodes.ts to hold Graph Node URLs
  * Add support for mantle and mantle-testnet Graph Nodes.
  * Fix `compare --build` to run `prepare` before compiling. This ensures the locally compiled hash matches the deployed hash.

# Output

```bash
mantisclone@mantisclone-Inspiron-7620:~/projects/payments-subgraph$ yarn subgraph monitor --network mainnet mantle mantle-testnet
yarn run v1.22.19
$ ts-node -r dotenv/config ./cli monitor --network mainnet mantle mantle-testnet
┌─────────┬──────────────────┬───────────┬──────────────────┬───────┐
│ (index) │     network      │ lastBlock │ lastIndexedBlock │ delay │
├─────────┼──────────────────┼───────────┼──────────────────┼───────┤
│    0    │    'mainnet'     │ 18420516  │     18420516     │   0   │
│    1    │     'mantle'     │ 17305267  │     17305262     │   5   │
│    2    │ 'mantle-testnet' │ 24577857  │     24577856     │   1   │
└─────────┴──────────────────┴───────────┴──────────────────┴───────┘
Done in 2.41s.
mantisclone@mantisclone-Inspiron-7620:~/projects/payments-subgraph$ yarn subgraph compare mainnet mantle mantle-testnet
yarn run v1.22.19
$ ts-node -r dotenv/config ./cli compare mainnet mantle mantle-testnet
┌────────────────┬──────────────────────────────────────────────────┬─────────┐
│    (index)     │                       hash                       │ current │
├────────────────┼──────────────────────────────────────────────────┼─────────┤
│    mainnet     │ 'QmXudVqWnRaRK7HvnE3exQeqTPWAiAJS3s2cxeH2QVaGAY' │  true   │
│     mantle     │ 'QmZxP68wejKtunVeSqyJCrXWJF8KVVRnrcHDL54gntJo5Q' │  true   │
│ mantle-testnet │ 'QmVwdvRqek3KHNwhfHjEwBuyvebUuvZTe881guxg3Kc2Xn' │  true   │
└────────────────┴──────────────────────────────────────────────────┴─────────┘
Done in 3.66s.
```

### CODE REVIEW

File: cli/commands/prepare.ts [hunk 1]
```diff
@@ -10,20 +10,24 @@ export const builder = () => {};
...
+  const manifest = getManifest(
+    getTheGraphChainName(network),
+    getRequestNetworkChainName(network),
+  );
+  if (!manifest) {
+    console.warn(`No contract found for ${network}`);
+  } else {
+    writeFile(`subgraph.${network}.yaml`, manifest);
+  }
+}
```
Comment (MantisClone) [inline cli/commands/prepare.ts:28]: I moved this logic to an exported function so I could access it from `compare.ts`

File: cli/lib/delay.ts [hunk 2]
```diff
@@ -41,27 +41,50 @@ const getLastBlockRpc = async (network: string) => {
...
-  );
+  if (network === "mantle-testnet") {
+    return 'https://rpc.testnet.mantle.xyz/';
+  }
+  else if (network === "mantle") {
+    return 'https://rpc.mantle.xyz';
+  }
+  else {
+    const { data } = await client.get<{ name: string; rpcUrls: string[] }[]>(
+      "https://api.request.finance/currency/chains",
```
Comment (MantisClone) [inline cli/lib/delay.ts:75]: I wonder if there's a better way to do this than relying on a Request Finance API call. Out of scope for this PR.

**Review by alexandre-abrioux — APPROVED** [review]

File: cli/lib/status.ts [hunk 3]
```diff
@@ -34,11 +34,28 @@ type QueryResponse = {
 };
 
 export const getStatus = async (network: string) => {
-  const response = await request<QueryResponse>(
-    "https://api.thegraph.com/index-node/graphql",
-    query,
-    { subgraph: `requestnetwork/request-payments-${network}` },
-  );
+  let response;
```
Comment (benjlevesque) [inline cli/lib/status.ts:37]: just a detail, but you could instead have a mapping for the root URL, based on the network key: 

```js
const graphNode = {
 "mantle-testnet": "",
 "mantle": ""
}
const nodeUrl = graphNode[network] || defaultUrl;
```

File: cli/lib/delay.ts (hunk 2 above)
Comment (benjlevesque) [reply cli/lib/delay.ts:75]: this is sort of related to the issue of the network being represented as a string that isn't standard, rather than a chainId.

File: cli/lib/delay.ts [hunk 4]
```diff
@@ -41,27 +41,50 @@ const getLastBlockRpc = async (network: string) => {
 };
 
 const getLastBlockTheGraph = async (network: string) => {
-  const data = await request(
-    `https://api.thegraph.com/subgraphs/name/requestnetwork/request-payments-${network}`,
-    query,
-  );
+  let data;
+  if (network === "mantle-testnet") {
```
Comment (benjlevesque) [inline cli/lib/delay.ts:45]: see comment in cli/lib/status.ts.
I think you can have a common config for the root URL.

**Review by benjlevesque — APPROVED** [review]

File: cli/lib/status.ts (hunk 3 above)
Comment (MantisClone) [reply cli/lib/status.ts:37]: @benjlevesque What do you think of this? https://github.com/RequestNetwork/payments-subgraph/pull/72/commits/326f25c309b843c899c64c73a7d7ee8e552c9035

I don't have time to finish and test it today so I moved the PR back to draft status.

Comment (benjlevesque) [reply cli/lib/status.ts:37]: looks good yes

**Comment by MantisClone** [comment]
After refactoring, commands still work:

```
mantisclone@mantisclone-Inspiron-7620:~/projects/payments-subgraph$ yarn subgraph monitor --network mainnet mantle mantle-testnet
yarn run v1.22.19
$ ts-node -r dotenv/config ./cli monitor --network mainnet mantle mantle-testnet
┌─────────┬──────────────────┬───────────┬──────────────────┬───────┐
│ (index) │     network      │ lastBlock │ lastIndexedBlock │ delay │
├─────────┼──────────────────┼───────────┼──────────────────┼───────┤
│    0    │    'mainnet'     │ 18420744  │     18420744     │   0   │
│    1    │     'mantle'     │ 17310693  │     17310689     │   4   │
│    2    │ 'mantle-testnet' │ 24579717  │     24579716     │   1   │
└─────────┴──────────────────┴───────────┴──────────────────┴───────┘
Done in 3.86s.
mantisclone@mantisclone-Inspiron-7620:~/projects/payments-subgraph$ yarn subgraph compare mainnet mantle mantle-testnet
yarn run v1.22.19
$ ts-node -r dotenv/config ./cli compare mainnet mantle mantle-testnet
┌────────────────┬──────────────────────────────────────────────────┬─────────┐
│    (index)     │                       hash                       │ current │
├────────────────┼──────────────────────────────────────────────────┼─────────┤
│    mainnet     │ 'QmXudVqWnRaRK7HvnE3exQeqTPWAiAJS3s2cxeH2QVaGAY' │  true   │
│     mantle     │ 'QmZxP68wejKtunVeSqyJCrXWJF8KVVRnrcHDL54gntJo5Q' │  true   │
│ mantle-testnet │ 'QmVwdvRqek3KHNwhfHjEwBuyvebUuvZTe881guxg3Kc2Xn' │  true   │
└────────────────┴──────────────────────────────────────────────────┴─────────┘
Done in 3.02s.
```

We'll see that deploy works after we merge. :crossed_fingers: :ship:
